/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.garden.model

import org.openapi.garden.model.Place

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param list 
 * @param version 
 */


data class AraContentPlacesGet200ResponseAllOfData (

    @Json(name = "list")
    val list: kotlin.collections.List<Place>? = null,

    @Json(name = "version")
    val version: kotlin.String? = null

)

