/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.garden.model

import org.openapi.garden.model.ChannelRefs

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param subtitle 
 * @param url 
 * @param map 
 * @param count 
 * @param utcOffset 
 * @param content 
 */


data class AraContentPagePlaceIdChannelsGet200ResponseAllOfData (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "subtitle")
    val subtitle: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "map")
    val map: kotlin.String? = null,

    @Json(name = "count")
    val count: kotlin.Int? = null,

    @Json(name = "utcOffset")
    val utcOffset: kotlin.Int? = null,

    @Json(name = "content")
    val content: kotlin.collections.List<ChannelRefs>? = null

)

