/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.garden.model

import org.openapi.garden.model.AraContentPagePlaceIdChannelsGet200ResponseAllOfData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param apiVersion 
 * @param version 
 * @param `data` 
 */


data class AraContentPagePlaceIdChannelsGet200Response (

    @Json(name = "apiVersion")
    val apiVersion: kotlin.Int? = null,

    @Json(name = "version")
    val version: kotlin.String? = null,

    @Json(name = "data")
    val `data`: AraContentPagePlaceIdChannelsGet200ResponseAllOfData? = null

)

