/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.garden.model

import org.openapi.garden.model.ChannelCountry
import org.openapi.garden.model.ChannelPlace

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param url 
 * @param website 
 * @param secure 
 * @param place 
 * @param country 
 */


data class Channel (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "website")
    val website: kotlin.String? = null,

    @Json(name = "secure")
    val secure: kotlin.Boolean? = null,

    @Json(name = "place")
    val place: ChannelPlace? = null,

    @Json(name = "country")
    val country: ChannelCountry? = null

)

