/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.garden.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param href 
 * @param subtitle 
 * @param map 
 */


data class ChannelPlaceRef (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "href")
    val href: kotlin.String? = null,

    @Json(name = "subtitle")
    val subtitle: kotlin.String? = null,

    @Json(name = "map")
    val map: kotlin.String? = null

)

