/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.garden.model

import org.openapi.garden.model.CountryPopularStationsItemsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param type 
 * @param itemsType 
 * @param items 
 */


data class CountryPopularStations (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "itemsType")
    val itemsType: kotlin.String? = null,

    @Json(name = "items")
    val items: kotlin.collections.List<CountryPopularStationsItemsInner>? = null

)

