/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.garden.model

import org.openapi.garden.model.ChannelPlaceRef
import org.openapi.garden.model.MoreRef
import org.openapi.garden.model.MoreRefPage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param href 
 * @param subtitle 
 * @param map 
 * @param type 
 * @param rightAccessory 
 * @param page 
 */


data class CountryPopularStationsItemsInner (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "href")
    val href: kotlin.String? = null,

    @Json(name = "subtitle")
    val subtitle: kotlin.String? = null,

    @Json(name = "map")
    val map: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "rightAccessory")
    val rightAccessory: kotlin.String? = null,

    @Json(name = "page")
    val page: MoreRefPage? = null

)

