/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.garden.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ip 
 * @param countryCode 
 * @param countryName 
 * @param regionCode 
 * @param regionName 
 * @param city 
 * @param zipCode 
 * @param timeZone 
 * @param latitude 
 * @param longitude 
 * @param metroCode 
 */


data class Geolocation (

    @Json(name = "ip")
    val ip: kotlin.String? = null,

    @Json(name = "country_code")
    val countryCode: kotlin.String? = null,

    @Json(name = "country_name")
    val countryName: kotlin.String? = null,

    @Json(name = "region_code")
    val regionCode: kotlin.String? = null,

    @Json(name = "region_name")
    val regionName: kotlin.String? = null,

    @Json(name = "city")
    val city: kotlin.String? = null,

    @Json(name = "zip_code")
    val zipCode: kotlin.String? = null,

    @Json(name = "time_zone")
    val timeZone: kotlin.String? = null,

    @Json(name = "latitude")
    val latitude: kotlin.Float? = null,

    @Json(name = "longitude")
    val longitude: kotlin.Float? = null,

    @Json(name = "metro_code")
    val metroCode: kotlin.Int? = null

)

