/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.garden.model

import org.openapi.garden.model.PlaceRef

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param leftAccessory 
 * @param leftAccessoryCount 
 * @param page 
 */


data class LeftPageRef (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "leftAccessory")
    val leftAccessory: kotlin.String? = null,

    @Json(name = "leftAccessoryCount")
    val leftAccessoryCount: kotlin.Int? = null,

    @Json(name = "page")
    val page: PlaceRef? = null

)

