/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.garden.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param geo 
 * @param url 
 * @param propertySize 
 * @param boost 
 * @param title 
 * @param country 
 */


data class Place (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "geo")
    val geo: kotlin.collections.List<kotlin.Float>? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null,

    @Json(name = "boost")
    val boost: kotlin.Boolean? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "country")
    val country: kotlin.String? = null

)

